name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
    name: Build
    runs-on: windows-latest

    env:
      OFFICIAL_BUILD: 'True'
      # Set the build number in MinVer.
      MINVERBUILDMETADATA: build.${{github.run_number}}
  
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
          
    - name: Restore dependencies
      run: dotnet restore 
      working-directory: ./src

    - name: Build
      run: dotnet build --no-restore 

    - name: Generate SBOM
      shell: pwsh
      run: |
        ls
        Invoke-WebRequest -Uri "https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-win-x64.exe" -OutFile "${env:RUNNER_TEMP}/sbom-tool.exe"
        & ${env:RUNNER_TEMP}/sbom-tool generate -b . -bc . -pn Test -pv 1.0.1 -ps Elijah_Nunez -nsb http://workflowtest/ -v Verbose
        ls ./_manifest/spdx_2.2/
        cat ./_manifest/spdx_2.2/manifest.spdx.json
      #Build and upload Artifacts
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        path: ./_manifest

    
    - name: Test
      run: dotnet test --no-build --verbosity normal